### ISSUE TITLE
Artifact, on open in linux without ROM

### ISSUE THREAD

**Issue by GabrielBRDeveloper** [wheremyfoodat/Panda3DS#121]
**OS:** LinuxMint 21.1
**Kernel:**  5.15.0-76-generic 

![image](https://github.com/wheremyfoodat/Panda3DS/assets/97042217/936b94ea-3bbb-4940-a886-d2f6064e1c95)

**Comment by wheremyfoodat** [comment]
How did you install this? Maybe try compiling from source?

**Comment by GabrielBRDeveloper** [comment]
Builded from source

**Comment by wheremyfoodat** [comment]
Does it work if you load a ROM eg Ocarina of Time? What's your GPU?

**Comment by GabrielBRDeveloper** [comment]
in the precompiled version, it doesn't even display the window.

**Comment by wheremyfoodat** [comment]
Yeah the precompiled builds aren't really portable because shipping software on Linux is not a fun experience

**Comment by wheremyfoodat** [comment]
Potentially fixed in #259?

**Comment by GabrielBRDeveloper** [comment]
Not resolved.

![image](https://github.com/wheremyfoodat/Panda3DS/assets/97042217/9b67c94e-35a9-45f8-bad9-8e220c45fb3b)

![image](https://github.com/wheremyfoodat/Panda3DS/assets/97042217/481ee091-1662-4bb5-9dad-bbc18b8c6202)

**Comment by wheremyfoodat** [comment]
Could you try loading a ROM? Also please post your specs and any important information if possible.

**Comment by GabrielBRDeveloper** [comment]
My system:

![image](https://github.com/wheremyfoodat/Panda3DS/assets/97042217/f02fca4e-c8ef-4c93-91b5-6130b69d93fc)

I will test Zelda Ocarina, and return with a feedback

**Comment by wheremyfoodat** [comment]
Thanks!

**Comment by GabrielBRDeveloper** [comment]
did error:

![image](https://github.com/wheremyfoodat/Panda3DS/assets/97042217/41ee25be-bb46-4674-9d1f-7f9622c8d37c)

`Unhandled SIGSEGV at rip 0x00007f62d19a9c9d
Falha de segmentação (imagem do núcleo gravada)
`

**Comment by wheremyfoodat** [comment]
Uh that's bad. Does this ROM run on Citra?

**Comment by GabrielBRDeveloper** [comment]
too  crash in recent citra version, i go to check  the rom file.

**Comment by GabrielBRDeveloper** [comment]
![image](https://github.com/wheremyfoodat/Panda3DS/assets/97042217/4535b05f-fd21-458e-b3e6-b8930fa73ab9)

**Comment by GabrielBRDeveloper** [comment]
It's working.

**Comment by GabrielBRDeveloper** [comment]
The  artifact is caused because is not none rendering in moment, on edit code in **emulator.cpp**:

```

void Emulator::runFrame() {
	if (running) {
		cpu.runFrame(); // Run 1 frame of instructions
		gpu.display();  // Display graphics

		// Send VBlank interrupts
		ServiceManager& srv = kernel.getServiceManager();
		srv.sendGPUInterrupt(GPUInterrupt::VBlank0);
		srv.sendGPUInterrupt(GPUInterrupt::VBlank1);

		// Run cheats if any are loaded
		if (cheats.haveCheats()) [[unlikely]] {
			cheats.run();
		}
	} else if (romType != ROMType::None) {
		// If the emulator is not running and a game is loaded, we still want to display the framebuffer otherwise we will get weird
		// double-buffering issues
		gpu.display();
	}
}


```

removing the `if (romType != ROMType::None) `

```

} else {
		// If the emulator is not running and a game is loaded, we still want to display the framebuffer otherwise we will get weird
		// double-buffering issues
		gpu.display();
	}

```

The artifact fades aways.

**Comment by wheremyfoodat** [comment]
OK then I am likely forgetting to clear a texture somewhere. I'll check it out.
Though thankfully the emu still works itself.
